FROM node:22-alpine as builder

WORKDIR /app

COPY package*.json ./
RUN npm install --production=false

COPY . .
RUN npm run build

FROM node:22-alpine as production

WORKDIR /app

COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package*.json ./

COPY --from=builder /app/dist /app/dist

EXPOSE 3000

CMD [ "npm", "start" ]
